using DevExpress.DashboardCommon;
using DevExpress.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data.Entity;

namespace TakipProjesi.Formlar
{
    public partial class Dashboard1 : DevExpress.DashboardCommon.Dashboard
    {
        public Dashboard1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            TakipProjesi.Entity.SatisDBEntities2 dbContext = new TakipProjesi.Entity.SatisDBEntities2();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.SalesTBL.Load();
            
        }
    }
}
