//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipProjesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbarTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AmbarTBL()
        {
            this.InvetoryTransactionsTBL = new HashSet<InvetoryTransactionsTBL>();
        }
    
        public int AmbarId { get; set; }
        public string Ad { get; set; }
        public string Konum { get; set; }
        public Nullable<int> Kapasite { get; set; }
        public string Sorumlu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvetoryTransactionsTBL> InvetoryTransactionsTBL { get; set; }
    }
}
