//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipProjesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvetoryTransactionsTBL
    {
        public int TransactionID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string TransactionTyppe { get; set; }
        public Nullable<int> WareHouse { get; set; }
    
        public virtual ProductTBL ProductTBL { get; set; }
        public virtual AmbarTBL AmbarTBL { get; set; }
    }
}
