//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipProjesi.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SatisDBEntities2 : DbContext
    {
        public SatisDBEntities2()
            : base("name=SatisDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campaigns> Campaigns { get; set; }
        public virtual DbSet<CategoryTBL> CategoryTBL { get; set; }
        public virtual DbSet<CustomerTBL> CustomerTBL { get; set; }
        public virtual DbSet<InvetoryTransactionsTBL> InvetoryTransactionsTBL { get; set; }
        public virtual DbSet<OrdersTBL> OrdersTBL { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<ProductTBL> ProductTBL { get; set; }
        public virtual DbSet<SalesRepresentativeTBL> SalesRepresentativeTBL { get; set; }
        public virtual DbSet<SalesTBL> SalesTBL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<AmbarTBL> AmbarTBL { get; set; }
    }
}
