//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipProjesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTBL()
        {
            this.InvetoryTransactionsTBL = new HashSet<InvetoryTransactionsTBL>();
            this.SalesTBL = new HashSet<SalesTBL>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Marka { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> StockQuantity { get; set; }
        public string Desccription { get; set; }
    
        public virtual CategoryTBL CategoryTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvetoryTransactionsTBL> InvetoryTransactionsTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesTBL> SalesTBL { get; set; }
    }
}
