//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipProjesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTBL
    {
        public int SaleID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string PaymentMethod { get; set; }
        public string ShippingAddress { get; set; }
        public string Status { get; set; }
        public Nullable<int> SalesRapID { get; set; }
    
        public virtual CustomerTBL CustomerTBL { get; set; }
        public virtual ProductTBL ProductTBL { get; set; }
        public virtual SalesRepresentativeTBL SalesRepresentativeTBL { get; set; }
    }
}
